os: Visual Studio 2015
configuration: Release

version: 0.0.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform:
  - Any CPU

before_build:
  - nuget restore

build:
  verbosity: minimal
  cmd: Alegri.Data.EF6.sln
