# master branch commits deploy on NuGet as beta

-
  branches:
    only:
      - develop

  version: 0.2.{build}

  environment:
    packageVersion: $env:buildVersion

  init:
    - ps: |
        $version = new-object System.Version $env:APPVEYOR_BUILD_VERSION
        $env:PackageVersion = "{0}.{1}.{2}-beta" -f $version.Major, $version.Minor, $version.Build

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '$(APPVEYOR_BUILD_VERSION)'
    assembly_file_version: '$(APPVEYOR_BUILD_VERSION)'
    assembly_informational_version: '$(PackageVersion)'

  configuration: Release

  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true


  before_build:
    - nuget restore

  build:
    verbosity: minimal
    project: Alegri.Data.EF6.sln

  after_build:
  - ps: nuget pack Alegri.Data.EF6.nuspec -version "$env:PackageVersion"

  test:
    assemblies:
      - 'tests\**.UnitTests.dll'
      - 'tests\**.IntegrationTests.dll'

  artifacts:
  - path: 'Alegri.Data.EF6.*.nupkg'
    name: Alegri.Data.EF6-NuGetPackage

  deploy:
    - provider: NuGet
      api_key:
        secure: nUr0+fG+AubyMq/gSKDeCzCEyeiJmHNmfaX+1FgGMbDvZzSm6oelRY3+xjaM+IO3
      artifact: Alegri.Data.EF6-NuGetPackage

# release branch
-
  branches:
    only:
    - master

  version: 0.2.{build}

  environment:
    packageVersion: $env:buildVersion

  init:
    - ps: |
        $version = new-object System.Version $env:APPVEYOR_BUILD_VERSION
        $env:PackageVersion = "{0}.{1}.{2}" -f $version.Major, $version.Minor, $version.Build

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '$(APPVEYOR_BUILD_VERSION)'
    assembly_file_version: '$(APPVEYOR_BUILD_VERSION)'
    assembly_informational_version: '$(PackageVersion)'

  configuration: Release

  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true


  before_build:
    - nuget restore

  build:
    verbosity: minimal
    project: Alegri.Data.EF6.sln

  test:
    assemblies:
      - 'tests\**.UnitTests.dll'
      - 'tests\**.IntegrationTests.dll'

  after_build:
  - ps: nuget pack Alegri.Data.EF6.nuspec -version "$env:PackageVersion"

  artifacts:
  - path: 'Alegri.Data.EF6.*.nupkg'
    name: Alegri.Data.EF6-NuGetPackage

  deploy:
    - provider: NuGet
      api_key:
        secure: nUr0+fG+AubyMq/gSKDeCzCEyeiJmHNmfaX+1FgGMbDvZzSm6oelRY3+xjaM+IO3
      artifact: Alegri.Data.EF6-NuGetPackage
      on:
        branch: master
        appveyor_repo_tag: true

# all other branches
# compile, test, release
-
  version: 0.2.{build}

  configuration: Release

  before_build:
  - nuget restore

  build:
    verbosity: minimal
    project: Alegri.Data.EF6.sln