# configuration for "master" branch
# build in Release mode and deploy to Azure
-
  branches:
    only:
      - master

-
  os: Visual Studio 2015
  configuration: Release

  before_build:
   - nuget restore

  build:
    verbosity: minimal
    project: Alegri.Data.EF6.sln