# configuration for "master" branch
# build in Release mode and deploy to Azure
-
  branches:
    only:
      - develop

  configuration: Release

# configuration for all branches starting from "dev-"
# build in Debug mode and deploy locally for testing
-
  branches:
    only:
      - master


platform: Any CPU
os: Visual Studio 2015
configuration: Release

before_build:
  - nuget restore

build:
  verbosity: minimal
  project: Alegri.Data.EF6.sln